language: java
language: ruby
sudo: required
addons:
 chrome: stable

services:
  - mysql

before_install:
  - mysql -u root --password="" < sql/imhungry.sql
  - gem update --system
  - gem install bundler
  - wget http://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root1234!') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -Dtest="info.*Test"
  - mvn test -Dtest="security.*Test"
  - mvn test -Dtest=DatabaseTest
  - mvn test -Dtest=SearchServletTest
  - mysql -u root --password="root1234!" < sql/imhungry.sql
  - mvn test -Dtest=LoginServletTest
  - mvn test -Dtest=ListServletTest
  - mvn test -Dtest=PrevSearchServletTest
  - mvn tomcat7:run &
  - sleep 10
  - cd Ruby/resources
  - cucumber
